name: Build
on: release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install minimal nightly
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        override: true
        toolchain: nightly
    - name: Build
      run: cargo build --release
      env:
        CARGO_TERM_COLOR: always
      with:
        toolchain: +nightly
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        asset_path: target/release/isac
        asset_name: isac
